version: '3'

services:
  api:
    build:
      context: .
    container_name: graphql-poc
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      DATABASE_URL: jdbc:mysql://db:3306/graphql_poc_db
      DATABASE_USER: root
      DATABASE_PASSWORD: root

  db:
    image: mysql:latest
    container_name: graphql-poc-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=graphql_poc_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
